id: P008188
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-17 13:06:52.545830
source_metadata:
  id: bdr:W25122
  title: ངོས་འཛིན་རྟགས་ཀྱི་རྣམ་བཤད
  author: ''
  volumes:
    cc4423fc6bae405f861ced5d557cf4b7:
      image_group_id: I4842
      title: ''
      volume_number: 1
      total_pages: 396
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
