id: IAA45415A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T15:15:16+00:00'
last_modified: '2022-06-09T05:06:48.750250+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W25122
  title: ངོས་འཛིན་རྟགས་ཀྱི་རྣམ་བཤད
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '2174':
      image_group_id: I4842
      title: ''
      total_pages: 396
      order: 1
      base_file: 2174.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
